config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations" 
  }

  root to: "conversations#index"
  
  resources :conversations, only: [:index, :new, :create, :destroy] 
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :characters, only: [:edit, :update]
  resources :backgrounds, only: [:edit, :update]
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


end

app/models/background.rb
class Background < ActiveHash::Base
  self.data = [
    { id: 1, name: '草原', image_url: 'default_background.jpg' },
    { id: 2, name: '食堂', image_url: '5919320i.jpg' },
    { id: 3, name: 'ラジオ室', image_url: '1688670i.jpg' },
    { id: 4, name: '港', image_url: '1988536i.jpg' },
    { id: 5, name: '部屋', image_url: '3122679i.jpg' },
    { id: 6, name: '森', image_url: '森.jpg' },
    { id: 7, name: 'ラウンジ', image_url: '11069179i.jpg' }
  ]

  def self.default_background
    find(1)
  end
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def edit
    @user = current_user
    @backgrounds = Background.all
  end

  def update
    @user = current_user
    if @user.update(user_params)
      sign_in @user, bypass: true
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:background_id)
  end
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/views/backgrounds/edit.html.erb
<%= render "shared/header" %>
<div class="default-background-color">
<%= form_with(model: @user, url: background_path(current_user.background.id), method: :patch, class: 'background-form') do |f| %>
  <div class="background-group">
    <div class="background-list">
      <% @backgrounds.each do |background| %>
        <div class="background-items">
          <div class="background-item">
            <%= image_tag background.image_url, alt: background.name %>
          </div>
          <div class="background-radio">
            <%= f.radio_button :background_id, background.id, id: "radio-#{background.id}" %>
            <label for="radio-<%= background.id %>"><%= background.name %></label>
          </div>
        </div>  
      <% end %>
    </div>
  </div>
  

  <div class="background-submit">
    <%= f.submit '更新する', class: 'character-btn' %>
  </div>
<% end %>
</div>