config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations" 
  }

  root to: "conversations#index"
  
  resources :conversations, only: [:index, :new, :create, :destroy] 
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :characters, only: [:edit, :update]
  resources :backgrounds, only: [:edit, :update]
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :conversations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :hobbies
  belongs_to :interests
  belongs_to :character
  belongs_to :background

  validates :username,     presence: true
  validates :character_id, presence: { message: 'を選択してください' }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers', on: :registration

  # showページに記述するため
  def hobbies_name
    Hobbies.find_by(id: hobbies_id)&.name
  end

  def interests_name
    Interests.find_by(id: interests_id)&.name
  end

  def character_name
    Character.find_by(id: character_id)&.name
  end
  # ここまで

  def background
    Background.find_by(id: background_id)
  end

  def user_background
    background || Background.default_background
  end

  # 更新時、パスワードを除外
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  @characters = Character.all

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  # 追加
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [:username, :email, :date_of_birth, :hobbies_id, :interests_id, :character_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  # super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_ownership, only: [:show, :edit]

  def show
    if user_signed_in?
      @user = current_user
      @character = current_user.character
    else
      redirect_to new_user_session_path, alert: 'ログインしてください。'
    end
  end

  def edit
    @user = current_user
    @character = current_user.character || current_user.build_character

    # ユーザーが存在しない場合は404エラーを返す
    render_not_found if @user.nil?
  end

  def update
    @user = current_user
    @character = current_user.character
    if @user.update(user_params)
      sign_in @user, bypass: true
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    conversations = @user.conversations
    conversations.each do |conversation|
      conversation.destroy
    end
    if @user.destroy
      conversations.destroy_all
      # 削除成功時の処理
      flash[:notice] = 'アカウントが削除されました'
      redirect_to root_path
    else
      # 削除失敗時の処理
      flash[:alert] = 'アカウントの削除に失敗しました'
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :date_of_birth, :hobbies_id, :interests_id, :character_id)
  end

  def check_ownership
    # ログイン中のユーザーと表示するユーザーが異なる場合はリダイレクト
    return if current_user.id == params[:id].to_i

    redirect_to root_path, alert: '他のユーザーのページにはアクセスできません。'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>
<div class="default-background-color">
<%= form_with(model: @user, url: user_path, method: :patch) do |f| %>
<div class="show-wrapper">
  <div class="left-section">
  <h1 class="form-header-text">
        ユーザー情報
  </h1>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">ユーザー名: <%= f.text_field :username, class:"show-text-f" %></div>
        </div>
    </div> 
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">メールアドレス: <%= f.email_field :email, class:"show-text-f" %></p></div>
        </div>
    </div>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">生年月日: <%= f.date_field :date_of_birth %></div>          
        </div>
    </div>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">趣味: 
            <%= f.select :hobbies_id, Hobbies.all.map { |h| [h.name, h.id] }, {}, class:'default-select' %>
          </div>
        </div>
    </div>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">関心事:  
            <%= f.select :interests_id, Interests.all.map { |i| [i.name, i.id] }, {}, class:'default-select' %>
          </div>
        </div>
    </div>  
    
    <div class="edit-button-container">
      <%= f.submit '更新する', class: 'edit-button' %>
    </div>
  <% end %>  
  </div>
  <div class="right-section">
    <div class="show-character-image">
      <%= image_tag @character.image_url, alt: @character.name %>
      <div class="character-info">
         <div class="show-text">キャラクター: <%= current_user.character_name %></div>
      </div>
    </div>
    <%=link_to 'キャラクター選択', edit_character_path(current_user.character), class: 'edit-button-c' %></li>
  </div>
</div>  
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="default-background-color">
<div class="show-wrapper">
  <div class="left-section">
    <h1 class="form-header-text">
        ユーザー情報
    </h1>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">ユーザー名: <%= current_user.username %></div>
        </div>
    </div> 
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">メールアドレス: <%= current_user.email %></div>
        </div>
    </div>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">生年月日: <%= current_user.date_of_birth %></div>
        </div>
    </div>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">趣味: <%= current_user.hobbies_name %></div>
        </div>
    </div>
    <div class="show-group">
        <div class="show-text-wrap">
          <div class="show-text">関心事: <%= current_user.interests_name %></div>
        </div>
    </div>
    <div class="edit-button-container">
      <%= link_to '編集', edit_user_path(current_user), class: 'edit-button-e' %>
    </div>
    <div class="show-delete">
      <%= form_with url: user_path(current_user), method: :delete do |f| %>
        <%= f.button 'アカウント削除', class: 'delete-button', id: 'delete-button' %>
      <% end %>
    </div>  
  </div>
  <div class="right-section">
    <div class="show-character-image">
      <%= image_tag @character.image_url, alt: @character.name %>
      <div class="character-info">
         <div class="show-text">キャラクター: <%= current_user.character_name %></div>
         <p>性格: <%= @character.profile1 %></p>
         <p>好きなもの: <%= @character.profile2 %> </p>
         <p>特徴: <%= @character.profile3 %> </p>
      </div>
    </div>
  </div>
</div> 
</div>