config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations" 
  }

  root to: "conversations#index"
  
  resources :conversations, only: [:index, :new, :create, :destroy] 
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :characters, only: [:edit, :update]
  resources :backgrounds, only: [:edit, :update]
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <div class="top-logo">
    <%= link_to "ChatterBox","/", class:"logo" %>
  </div>
  <% if user_signed_in? %>
    <ul class="menu-lists">
      <li><%=link_to "マイページ",user_path(current_user) , class:"menu-list" %></li>
      <li><%=link_to 'キャラクター選択', edit_character_path(current_user.character), class: 'menu-list' %></li>
      <li><%=link_to "背景設定", edit_background_path(current_user), class:"menu-list" %></li>
    </ul>  
  <% end %>
</header>
<div class="smart-header">
  <%= link_to "ChatterBox","/", class:"smart-logo" %>
</div>

app/views/shared/_side-bar.html.erb
<% if user_signed_in? %>
  <div class="side_bar">
    <div class="history">会話履歴</div>    
    <div class="side_bar_top">      
      <div class="conversation-history">
        <% @conversations.each do |conversation| %>
          <div class="conversation">
            <%= link_to conversation.content, "#", class: "conversation-link", data: { content: conversation.content, chatbot_reply: conversation.chatbot_reply } %>
            <%= link_to conversation_path(conversation), remote: true, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "delete-link" do %>
            <i class="fa-solid fa-eraser icon"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="side_bar_footer">
      <%= form_with(url: destroy_user_session_path, method: :delete) do |f| %>
        <%= f.submit 'ログアウト', class: 'logout-button' %>
      <% end %>
    </div>
  </div>
<% end %>